#!/bin/bash
# This script is executed at boot time after VyOS configuration is fully
# applied. Any modification required to work around unfixed bugs or use
# services not available through the VyOS CLI system can be placed here.

if [ -d "/home/vyos" ]; then
# Add dotfiles for home directory
  tee /home/vyos/.gitconfig <<END >/dev/null
[init]
  defaultBranch = "main"
[core]
  sshCommand = "ssh -i /config/secrets/id_rsa"
[safe]
  directory = "/config"
[commit]
  gpgSign = true
[gpg]
  format = "ssh"
[user]
  email = "eko.pur25@gmail.com"
  name = "trosvald"
  signingKey = "/config/secrets/id_rsa.pub"
END
  chown vyos:users /home/vyos/.gitconfig

  tee -a /home/vyos/.bash_aliases <<END >/dev/null
export SOPS_AGE_KEY_FILE=/config/secrets/age.key
alias podman="sudo podman"
END
  chown vyos:users /home/vyos/.bash_aliases

  if [ -d "/home/vyos/.ssh" ]; then
    ssh-keyscan -H github.com > /home/vyos/.ssh/known_hosts
    chown vyos:users /home/vyos/.ssh/known_hosts
  fi
fi

# Disable EEE on network interfaces as a workaround to i225/i226 issues
while read -r interface
do
  sudo ethtool -G eth0 tx 4096 rx 4096
  sudo ethtool -G eth1 tx 8192 rx 8192
  sudo ethtool -G eth2 tx 8192 rx 8192
done