#!/bin/sh
# This script is executed at boot time before VyOS configuration is applied.
# Any modifications required to work around unfixed bugs or use
# services not available through the VyOS CLI system can be placed here.

# TODO: Remove if issues don't come back, turn back on if they do
# Clean dangling container network files
# rm /var/lib/cni/networks/containers/10.5.*

# Fix for containers requiring a custom user/group id
# and Vyos not preserving file perms on upgrade
mkdir -p /tmp/bind/cache
sudo chown -R messagebus /tmp/bind/cache
mkdir -p /config/tftpboot
# curl -L -o /config/tftpboot/ipxe.efi http://boot.ipxe.org/ipxe.efi
# curl -L -o /config/tftpboot/undionly.kpxe http://boot.ipxe.org/undionly.kpxe
sudo chown -R tftp:tftp /config/tftpboot/
mkdir -p /tmp/onepassword/data
chown -R 999 /tmp/onepassword/data

# Mount USB backup drive
backupdest=/media/usb-backup
sudo mkdir -p "$backupdest"
sudo mount.exfat-fuse -o rw,uid=vyos,gid=vyattacfg /dev/disk/by-id/usb-SanDisk__Cruzer_Fit_02000904062321085848-0:0-part1 "$backupdest"
